INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, CATEGORY) VALUES ('111-AA', 'Widget', 'Cool Widget', 'Widget');
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, CATEGORY) VALUES ('112-AB', 'Widget-2', 'Really Cool Widget', 'Widget');
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, CATEGORY) VALUES ('000-OO', 'Spam', 'Classic Canned Meat Gluten Free. Fully cooked, ready to eat--cold or hot.', 'Food');
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, CATEGORY) VALUES ('123-SF', 'Apple iPad Air 2', 'Apple iPad Air 2 tablet, featuring a thin Retina display and antireflective coating.', 'Electronics');
INSERT INTO PURCHASEORDER (COMMENT, ORDERDATE) VALUES ('First Order, Yea!', '2017-03-31');
INSERT INTO ORDERITEM (PRODUCTID, QUANTITY, ITEMPRICE, PURCHASEORDERID, INDEX) VALUES (1, 1, 1.99, 1, 0);
INSERT INTO ORDERITEM (PRODUCTID, QUANTITY, ITEMPRICE, PURCHASEORDERID, INDEX) VALUES (2, 1, 2.99, 1, 1);
